### ISSUE TITLE
Add redirect_uri to POST for token endpoint

### ISSUE THREAD

**Issue by davidnhale** [FamilySearch/familysearch-javascript-sdk#145]
With an architectural FamilySearch change in October, apps that relied on the token endpoint to pass their users to FamilySearch now find that their users have to login twice: once when they first authenticate and use the API in the app and again when they are redirected to FamilySearch. Unfortunately workarounds fail because the POST to the token endpoint fails because there is no `redirect_uri` provided. According to the [OAuth2 docs](https://tools.ietf.org/html/rfc6749#section-4.1.3)  this should be a required parameter, but in the FamilySearch docs this wasn't mentioned.

Can you please add the `redirect_uri` to the token endpoint? You will need to check to be sure that it is in scope and available at the time it is called. Apps which are not configured to use CIS for authentication won't be impacted by adding this extra parameter.
<img width="1189" alt="token_endpoint_400 1" src="https://cloud.githubusercontent.com/assets/5315740/11699637/898e0486-9e82-11e5-933c-0d03233f9df0.png">

**Comment by justincy** [comment]
> apps that relied on the token endpoint to pass their users to FamilySearch

I didn't know that was possible. Is that documented on the developer's website?

> You will need to check to be sure that it is in scope and available at the time it is called.

I don't understand what the subject of this sentence is. What needs to be in scope?

Also, how should I test this? Is this a feature that needs to be enabled for an app like the password flow does? Can I test this on sandbox?

Is it okay if v2 of the SDK is the only one that gets updated?

**Comment by jimmyz** [comment]
The requirement of the redirect_uri parameter will be updated on the developer website in order to come current with the OAuth2 specification, but it won't be enforced for the default configuration as it would break many clients. The requirement will likely be enforced with the switch to OpenID Connect.

In order to test the configuration that does enforce the requirement, it can be configured on an app key. Just make a request to devsupport@familysearch.org. Best way to describe the configuration is "app key configured to use CIS as an OpenID provider."

**Comment by justincy** [comment]
I submitted a fix. Pretty trivial. https://github.com/FamilySearch/familysearch-javascript-sdk/commit/a916797b9bb5367b94c9c94c056cddefb6d610dd

Though I still don't understand what this has to do with redirecting users to FamilySearch.

**Comment by justincy** [comment]
I just released the fix for this. Version 2.4.2 will be available on the CDN in a few hours.
