### ISSUE TITLE
Publish to bower and npm

### ISSUE THREAD

**Issue by DallanQ** [FamilySearch/familysearch-javascript-sdk#17]

**Comment by justincy** [comment]
We can setup Travis to automatically publish to npm via deployments: http://docs.travis-ci.com/user/deployment/releases/

**Comment by justincy** [comment]
This is already published to bower.

**Comment by jimmyz** [comment]
I just updated the travis config with the account for publishing the nom package. As long as the API token is set correctly, we should be good to go. I haven't tested this, and it is set to only trigger upon a tagged release.

**Comment by justincy** [comment]
We'll test it and make sure it works before we release 1.0. When the jsDelivr pr is merged I'll tag another beta release to test both integrations.

**Comment by justincy** [comment]
@jimmyz does the package need to exist on npm before publishing the first time?

**Comment by justincy** [comment]
It appears that the package does not need to exist first, but I'm not positive. I guess we'll find out the first time it runs.

**Comment by justincy** [comment]
I'm struggling with a few things right now. Mainly, the current release workflow has too many steps and is error prone.

First you have to bump the version number in `package.json` and commit on master. Then you wait for the build to run, making sure tests pass and `gh-pages` are updated. Then you create a github release with a new version tag, making sure it's based off of the latest `gh-pages` commit and not the latest commit on `master`. Releases are tagged on `gh-pages` because that's where the docs and js files for distribution are. If `master` is tagged then the users and jsDelivr have nothing to download.

That just creates releases on Github and allows jsDelivr to update. That flow doesn't publish to npm. Travis is setup to only run the npm deploy command on tagged commits. But tags are done on the `gh-pages` branch and Travis appropriately ignore all activity on `gh-pages`. So nothing happens. The obvious solution would be to run the npm deploy on master every time, except then it would run and fail often. Unless we changed our workflow and only ever committed to master once a release was ready.

I guess I'll remove the tag restriction on the npm deploy to see what happens. I don't really know how it will behave.

**Comment by justincy** [comment]
And it would be nice if we could find a way for Github release to be done automatically so that we don't have to remember to tag `gh-pages

**Comment by justincy** [comment]
@jimmyz I think the package needs to exist. The [deploy failed](https://travis-ci.org/FamilySearch/familysearch-javascript-sdk/builds/70078141) with a 404.

**Comment by jimmyz** [comment]
Package exists now.
https://www.npmjs.com/package/familysearch-javascript-sdk

**Comment by justincy** [comment]
When I pushed a commit without updating the version, the npm deploy accurately detected that the version numbers matched and didn't attempt to update. However, when I did bump the version number, it tried to update and failed again with a 404/500 as it did before the package existed. :disappointed:

**Comment by justincy** [comment]
I've opened an [issue ](https://github.com/npm/npm/issues/8879)on npm to ask about this.

The only other thing I can think of would be to give my [npm user](https://www.npmjs.com/~justincy) access to the repo so that I can debug. I found the [commands](https://github.com/travis-ci/dpl/blob/master/lib/dpl/provider/npm.rb) travis uses to npm deploy so debug ought to be fairly simple.

**Comment by justincy** [comment]
Closed by c41def1ce0f4b50650182bce0c850837a53e5410
